### ISSUE TITLE
document recommended way to merge multiple consensus peak files from ASPEN to create one file for TOBIAS

### ISSUE THREAD

**Issue by kelly-sovacool** [CCBR/CCBR_tobias#9]
Are the default options from [bedtools merge](https://bedtools.readthedocs.io/en/latest/content/tools/merge.html) good enough for this use case, or are there other methods we should consider?

@kopardev

**Comment by Krithika-Bhuvan** [comment]
Found the answer on the TOBIAS FAQ (https://github.com/loosolab/TOBIAS/wiki/FAQ) and I quote below:

**What peak-file should I use as input?**
You should use any .bed-file containing open chromatin regions from peak-calling, e.g. from MACS2 or similar. If you are planning to compare several conditions with each other, e.g. `WT.bam` with `treatment.bam`, you should obtain the peaks `WT_peaks.bed` and `treatment_peaks.bed` for each condition, and merge these using e.g. bedtools:
```
cat WT_peaks.bed treatment_peaks.bed | bedtools sort | bedtools merge > merged_peaks.bed
```
You should then use 'merged_peaks.bed' throughout the TOBIAS tools.

**Comment by Krithika-Bhuvan** [comment]
Here is a simple bash script in case anyone is interested
```
#!/bin/bash

#SBATCH --partition=norm
#SBATCH --job-name=tobias_merge_bed
#SBATCH --time=48:00:00
#SBATCH --cpus-per-task=4
#SBATCH --mem=80g
#SBATCH --gres=lscratch:200

# SETTINGS TO CHANGE
consensus_bed_dir="/data/CCRCCDI/analysis/ccrtegs4/atac/01_aspen/output3/results/peaks/genrich/"
out_dir="/data/CCRCCDI/analysis/ccrtegs4/atac/09_tobias/"
OUTBED=$out_dir"merged_peaks.bed"

## STEPS - load bedtools module
module load bedtools
cd $consensus_bed_dir

echo "Found these files:"
ls *.genrich.consensus.bed

echo "Sort and merge these bed files:"
cat *.genrich.consensus.bed | bedtools sort | bedtools merge > $OUTBED

#call this script like this
#sbatch /data/CCRCCDI/analysis/ccrtegs4/scripts/script_merge_bed_for_tobias.sh
```
